In [1]:
import numpy as np

In [3]:
lista =[1,2]
lista

[1, 2]

In [4]:
lista*2

[1, 2, 1, 2]

In [6]:
arr= np.arange(0,10)
arr2=arr.copy()
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Operaciones

Multiplicacion

In [7]:
arr2*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

suma

In [9]:
arr2+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

otras

In [10]:
arr+arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [12]:
arr/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [15]:
matriz=arr.reshape(2,5)
matriz2=matriz.copy()
matriz2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
matriz+matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [17]:
matriz*matriz2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [19]:
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [20]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])

In [21]:
np.array([[1,2,3],[4,5,6],[7,8,9]]).ndim

2

In [22]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])