In [1]:
import numpy as np

In [4]:
arr= np.random.randint(1,20,10)

In [6]:
matriz = arr.reshape(2,5)
matriz

array([[ 1,  3, 18, 16, 19],
       [ 8,  1,  3, 12,  4]])

In [7]:
arr.max()

19

In [9]:
matriz.max(1)

array([19, 12])

In [10]:
matriz.max(0)

array([ 8,  3, 18, 16, 19])

poscion donde se encuentra el maximo argumento

In [11]:
arr.argmax()

4

In [12]:
matriz.argmax()


4

cero por columna

In [13]:
matriz.argmax(0)

array([1, 0, 0, 0, 0])

1 por fila

In [14]:
matriz.argmax(1)

array([4, 3])

minimo valor

In [15]:
arr.min()

1

In [22]:
matriz.min(0)

array([ 1,  1,  3, 12,  4])

In [23]:
matriz.min(1)

array([1, 1])

posicion del minimo valor

In [18]:
arr.argmin()

0

In [24]:
matriz.argmin(0)

array([0, 1, 1, 1, 1])

In [21]:
matriz.argmin(1)

array([0, 1])

In [25]:
arr

array([ 1,  3, 18, 16, 19,  8,  1,  3, 12,  4])

Diferencia entre el menor y el mayor

In [26]:
arr.ptp()

18

In [29]:
matriz

array([[ 1,  3, 18, 16, 19],
       [ 8,  1,  3, 12,  4]])

Diferencia del manor y el mayor por columna

In [27]:
matriz.ptp(0)

array([ 7,  2, 15,  4, 15])

In [28]:
matriz.ptp(1)

array([18, 11])

PErcentil  la mediana con 50

In [31]:
np.percentile(arr,50)

6.0

In [33]:
arr.sort()
arr

array([ 1,  1,  3,  3,  4,  8, 12, 16, 18, 19])

mediam

In [34]:
np.median(arr)

6.0

In [35]:
np.median(matriz,1)

array([ 3., 16.])

Desviación estandar

In [37]:
np.std(arr)

6.800735254367722

la desviacion estar elevado al 2 es igual a la variaza 

In [39]:
np.std(arr)**2

46.25000000000001

Varianza

In [38]:
np.var(arr)

46.25

La media

In [41]:
np.mean(arr)

8.5

Concatenar

In [42]:
a= np.array([[1,2],[3,4]])
b= np.array([5,6])

In [43]:
np.concatenate((a,b),axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [44]:
a.ndim
b.ndim

1

In [45]:
b= np.expand_dims(b,axis=0)

In [46]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
b

array([[5, 6]])

In [47]:
np.concatenate((a,b),axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [49]:
b.T

array([[5],
       [6]])

In [50]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])