In [1]:
import numpy as np

In [6]:
#arr = np.array([1,2,3,4],dtype='float64') Sea crea de una vez con el tipo de dato
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

Se cambia el tipo de dato

In [7]:
arr.astype(np.float64)

array([1., 2., 3., 4.])

Booleano

In [8]:
arr = np.array([1,2,3,4])
arr.astype(np.bool_)

array([ True,  True,  True,  True])

String

In [9]:
arr = np.array([1,2,3,4])
arr.astype(np.string_)

array([b'1', b'2', b'3', b'4'], dtype='|S21')

string a int

In [10]:
arr = np.array(['1','2','3','4'])
arr.astype(np.int8)

array([1, 2, 3, 4], dtype=int8)

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])